### ISSUE TITLE
CloudWatchLog Error Incomplete Signature Exception

### ISSUE THREAD

**Issue by milosradovanovic** [callstats-io/fluentd-kubernetes-cloudwatch#2]
First I created IAM policy then I  followed the steps . The result is as follows:

Kubernetes container has environment variables: 
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION 
with correct values.

Container is started with success but can't flush the buffer. Error message looks as follows

2016-12-30 15:51:39 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-12-30 15:52:11 +0000 error_class="Aws::CloudWatchLogs::Errors::IncompleteSignatureException" error="Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter.

Region I am trying to push the logs to is eu-west-1 if that is important info

**Comment by eljasala** [comment]
Could you post your DaemonSet, ConfigMap and the IAM policy you are using?

**Comment by milosradovanovic** [comment]
I was able to solve this couple of hours ago. I deleted secrets previously created using --from-file  (as described in README) and used --from-literal instead. This solved the problem. We can close this issue. Thanks for the support.

I used templates fom ConfigMap and DeamonSet from the repo and policy used was AWS CW Full Access.
