### ISSUE TITLE
Configuration references non existant image

### ISSUE THREAD

**Issue by andrew-jones** [callstats-io/fluentd-kubernetes-cloudwatch#6]
Default config points at, ${IMAGE_NAME:=callstats/fluentd-kubernetes-cloudwatch:v1.1.2}

Last versioned image tag pushed to docker hub is v1.0.1

**Comment by tuananh** [comment]
Should be fixed in this PR https://github.com/callstats-io/fluentd-kubernetes-cloudwatch/pull/12
